image: node

pipelines:
  default:
  - parallel:
    - step:
        name: Build and Test Surfbutler
        caches:
        - node
        script:
        - cd surfbutler
        - yarn install
        - yarn test

    - step:
        name: Build and Test Frontend
        caches:
        - node
        script:
        - cd landing-page
        - yarn install
        - yarn test
        - yarn build
        artifacts:
        - landing-page/dist/**

  - step:
      name: Deploy Surfbutler
      deployment: staging
      branches:
      - master
      caches:
      - node
      script:
      - cd surfbutler
      - yarn install
      - yarn test
      - apt-get update && apt-get install -y zip
      - zip -r surfbutler.zip .
      # Update lambda code and publish a new version
      - pipe: atlassian/aws-lambda-deploy:0.2.1
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_REGION
          FUNCTION_NAME: $AWS_FUNCTION_NAME
          COMMAND: 'update'
          ZIP_FILE: 'surfbutler.zip'

      # Read results from the update pipe into environment variables
      - source pipe.meta.env

      # Point an alias to the new lambda version
      - pipe: atlassian/aws-lambda-deploy:0.2.1
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_REGION
          FUNCTION_NAME: $AWS_FUNCTION_NAME
          COMMAND: 'alias'
          ALIAS: 'staging'
          VERSION: '${function_version}'

  - step:
      name: Deploy Frontend
      branches:
      - master
      script:
      - pipe: atlassian/aws-s3-deploy:0.2.1
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_REGION
          S3_BUCKET: "surfbutler.io"
          LOCAL_PATH: "landing-page/dist"
          ACL: "public-read"
          CACHE_CONTROL: "max-age=3600"
          EXPIRES: "2018-10-01T00:00:00+00:00"
          DELETE_FLAG: "true"
          EXTRA_ARGS: "--follow-symlinks"
